server:
  port: 8010

spring:
  application:
    name: message-sender

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: redis
      port: 6379

message:
  stream: message-stream
  group: message-group

redis:
  stream:
    message:
      key: message-stream
      group: message-group
      poll-timeout-ms: 500
      batch-size: 10
      consumer: ${HOSTNAME}   # 컨테이너마다 자동으로 다른 consumer

logging:
  level:
    root: INFO